### ISSUE TITLE
How to use foreign keys in select queries?

### ISSUE THREAD

**Issue by Meldiron** [wwwouter/typed-knex#15]
**Issue type:**

[X] Question
[ ] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[ ] Postgres
[ ] MSSQL
[X] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**
These are my table definitions:
```
import { Column, Table } from '@wwwouter/typed-knex';

@Table('company')
export class TableCompany {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'tag' })
  tag: string | null;
  @Column({ name: 'email' })
  email: string | null;
  @Column({ name: 'password' })
  password: string | null;
  @Column({ name: 'created_at' })
  createdAt: Date;
}

@Table('users')
export class TableUsers {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'email' })
  email: string | null;
  @Column({ name: 'password' })
  password: string | null;
  @Column({ name: 'activation_code' })
  activationCode: string | null;
  @Column({ name: 'google_data' })
  googleData: string | null;
  @Column({ name: 'facebook_data' })
  facebookData: string | null;
  @Column({ name: 'company_id' })
  companyId: TableCompany | null;
  @Column({ name: 'created_at' })
  createdAt: Date;
}
```

That means inside users table there is company_id which is foreign key to company table (id column).
I want to create this query: (I want to select company_id on purpose, I know it is not needed as I already have it in some varaible)
```
SELECT id from users WHERE company_id = ?
```

I writed code like this:
```
const userData = await SQLManager.typedKnex
      .query(TableUsers)
      .select((r) => [r.id])
      .where((r) => r.companyId.id, "4")
      .limit(1)
      .getFirstOrNull();
```

Problem is, it creates this query:
```
select `users`.`id` as `id` from `users` where `companyId`.`id` = ? limit ?
```
(and throws error `Error: Unknown column 'companyId.id' in 'where clause'`)

How do I write correct queries when my query includes foreign key column?

**Comment by wwwouter** [comment]
When I write my table class I always add two columns like this:
```
 @Column({ name: 'company_id' })
  company: TableCompany | null;
 @Column({ })
  company_id: number | null;
```
Now you can do ` .where((r) => r.company_id, "4")`

Your example can work, but you have to join the companies table, but that's probably not what you want in this case.

**Comment by Meldiron** [comment]
Thanks, that is great solution.
