### ISSUE TITLE
Update with aliases

### ISSUE THREAD

**Issue by Meldiron** [wwwouter/typed-knex#16]
**Issue type:**

[X] Question
[ ] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[ ] Postgres
[ ] MSSQL
[X] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**
These are my table definitions:
```
import { Column, Table } from '@wwwouter/typed-knex';

@Table('company')
export class TableCompany {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'tag' })
  tag: string | null;
  @Column({ name: 'email' })
  email: string | null;
  @Column({ name: 'password' })
  password: string | null;
  @Column({ name: 'created_at' })
  createdAt: Date;
}

@Table('users')
export class TableUsers {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'email' })
  email: string | null;
  @Column({ name: 'password' })
  password: string | null;
  @Column({ name: 'activation_code' })
  activationCode: string | null;
  @Column({ name: 'google_data' })
  googleData: string | null;
  @Column({ name: 'facebook_data' })
  facebookData: string | null;
  @Column({ name: 'company_id' })
  companyId: TableCompany | null;
  @Column({ name: 'created_at' })
  createdAt: Date;
}
```

I would like to write query:
```
UPDATE users SET email = ?, activation_code = ? WHERE id = ?
```

I wrote code like this:
```
    const newData = new TableUsers();
    newData.email = 'NEW EMAIL';
    newData.activationCode = '543245632';

    await SQLManager.typedKnex
      .query(TableUsers)
      .updateItemByPrimaryKey(1, newData);
```

Problem is, it creates this query:
```
update `users` set `email` = ?, `activationCode` = ? where `id` = ?
```
(and throws error `Error: Unknown column 'activationCode' in 'field list'`. Problem is `activationCode` instead of `activation_code`)

How do I write correct update queries?

**Comment by wwwouter** [comment]
The update and insert queries weren't under test, so this flew under the radar. I added tests and fixed this issue. Can you install v2.15.0 and see if this works for you?

**Comment by Meldiron** [comment]
Thanks seems to work perfectly. Fixed all scenarios where I use update and insert.
