### ISSUE TITLE
.orderBy() on timestamp

### ISSUE THREAD

**Issue by Meldiron** [wwwouter/typed-knex#20]
**Issue type:**

[X] Question
[X] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[ ] Postgres
[X] MSSQL
[ ] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**

Table definition:
```
@Table('users')
export class TableUsers {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'email' })
  email: string | null;
  @Column({ name: 'created_at' })
  createdAt: Date;
}
```

Code:
```
SQLManager.typedKnex.query(TableUsers).orderBy((i) => i.createdAt);
```

Error (typescript error):
```
Type 'TransformPropertiesToFunction<Required<Date>, [a: { name: "createdAt"; nullable: true; }]>' is not assignable to type '() => unknown'.
  Type 'TransformPropertiesToFunction<Required<Date>, [a: { name: "createdAt"; nullable: true; }]>' provides no match for the signature '(): unknown'.ts(2322)
```
(error is on `i.createdAt`)

If I try to orderBy `i.id` or `i.email` it works, it only has problem with date type.

**Comment by wwwouter** [comment]
Thanks for testing it with Dates 👍 

Can you see if v2.17.0 fixes your problem?

**Comment by Meldiron** [comment]
Thanks 👍
Error is gone and sql query looks correct.
