### ISSUE TITLE
Autocomplete not working properly on `findByPrimaryKey`

### ISSUE THREAD

**Issue by Meldiron** [wwwouter/typed-knex#22]
**Issue type:**

[X] Question
[X] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[ ] Postgres
[ ] MSSQL
[X] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**

Table definition (simplified):
```
@Table('users')
export class TableUsers {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'settings_email' })
  settingsEmail: string | null;
  @Column({ name: 'settings_full_name' })
  settingsFullName: string | null;
  @Column({ name: 'settings_birth_date' })
  settingsBirthDate: Date | null;
  @Column({ name: 'settings_nickname' })
  settingsNickname: string | null;
  @Column({ name: 'settings_photo' })
  settingsPhoto: string | null;
}
```

My code:
```
const userData = await SQLManager.typedKnex
      .query(TableUsers)
      .findByPrimaryKey(userId, (r) => [
        r.settingsBirthDate,
        r.settingsEmail,
        r.settingsFullName,
        r.settingsNickname,
        r.settingsPhoto,
      ]);
```

Problem: Autocomplete does not work, more info screenshot:
![image](https://user-images.githubusercontent.com/19310830/95068318-6d9a6d00-0705-11eb-97ed-e20db42cc07a.png)

If I write it like this, autocomplete work:
![image](https://user-images.githubusercontent.com/19310830/95068359-7e4ae300-0705-11eb-970b-682b9a70a062.png)

**Comment by wwwouter** [comment]
The difference is that `findByPrimaryKey` returns `object | void` while `getFirstOrNull` returns `object | null`.
Since TypeScript has optional chaining, VSCode started to support auto-completion of the second one.

Returning `void` was an old design decision, which is not relevant anymore. I updated this in v2.18.0 to return `null`.

**Comment by Meldiron** [comment]
![image](https://user-images.githubusercontent.com/19310830/99372516-909d6c80-28c0-11eb-932d-bd70c3bce497.png)


After update everything works perfectly. Thanks for the update.
