### ISSUE TITLE
Joined table is automatically flattened

### ISSUE THREAD

**Issue by mannol** [wwwouter/typed-knex#23]
**Issue type:**

[x] Question
[x] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[x] Postgres
[ ] MSSQL
[ ] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Knex.js version:**
0.21.6

**Steps to reproduce or a small repository showing the problem:**

I have a schema defined like:

```ts
@Table('images')
export class Image {
  @Column({ primary: true })
  public id?: string
  @Column()
  public url?: string
  @Column()
  public mimeType?: string
  @Column()
  public width?: number
  @Column()
  public height?: number
  @Column()
  public fileSize?: number

  @Column()
  public createdAt?: Date
  @Column()
  public updatedAt?: Date
  @Column()
  public deletedAt?: Date | null
}


@Table('users')
export class User {
  @Column({ primary: true })
  public id?: string

  // ... other fields

  @Column({ name: 'imageId' })
  public image?: Image
  @Column()
  public imageId?: string
}
```

When I do the following query:

```ts
typedKnex
  .query(User)
  .where((c) => c.id, 'someid')
  .leftOuterJoinColumn((c) => c.image)
  .getFirstOrNull()
  .then((user) => console.log(user, user.image))
```

`user.image` is **undefined** while `user` contains flattened fields from image. What am I doing wrong?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] Postgres
    [ ] MSSQL

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by wwwouter** [comment]
It's best to always use `.select` 

```
const user = await typedKnex
        .query(User)
        .where((c) => c.id, 'someid')
        .leftOuterJoinColumn((c) => c.image)
        .select(i => i.image.id)
        .getFirstOrNull();


    console.log(user, user?.image?.id);
```
In this case you still need to to check if `image` has a value, because when doing an `OUTER JOIN` there is a chance `users.imageId` is `NULL`.

Does this help?

**Comment by wwwouter** [comment]
@mannol Can this be closed?

**Comment by mannol** [comment]
I have since moved away from knex. Thank you for your trouble tho. This can be closed
