### ISSUE TITLE
.singleOrNull without .select does not show | null typing

### ISSUE THREAD

**Issue by voinik** [wwwouter/typed-knex#39]
**Issue type:**

[ ] Question
[x] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[x] Postgres
[ ] MSSQL
[ ] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Knex.js version:**  0.21.8

**Steps to reproduce or a small repository showing the problem:**
 See bug 2 in https://github.com/voinik/typedKnexBugTest/tree/master

In short:
```ts
    // Notice the ({..}) | null in the typing if you hover over the variable
    const fullyWrittenSubscription = await typedKnex.query(Subscription)
        .select('createdAt', 'id', 'paymentProviderCustomerReferenceId', 'updatedAt')
        .where('id', subscription1.id)
        .getSingleOrNull();

    // Notice the typing is only RemoveObjectsFrom<Subscription>, and no | null if you hover over the variable
    const shortHandSubscription = await typedKnex.query(Subscription)
        .where('id', subscription1.id)
        .getSingleOrNull();
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] Postgres
    [ ] MSSQL

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by wwwouter** [comment]
Some missing parentheses .. Fixed in 4.4.1!

**Comment by wwwouter** [comment]
@voinik Can this be closed?

**Comment by voinik** [comment]
> @voinik Can this be closed?

@wwwouter Yesss
