### ISSUE TITLE
MS Code Freezing with Typed Knex but fine without

### ISSUE THREAD

**Issue by tecorraltd** [wwwouter/typed-knex#40]
**Issue type:**

[ ] Question
[x ] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[x ] MySQL

typed-knex version: 4.4.1
Knex.js version: 0.21.21

Issue:

Hi, this library looks like just what I need but I'm finding MS Code freezes every time I hover over types to get the intellisense. If I comment out the typed-knex query and restart Code it's fine again. As soon as I uncomment it starts slowing down. When I checked Task Manager it looks like either there's a memory leak or it's just going to use a lot more than it should. I gave it a good couple minutes and three attempts to give it time to load up but it didn't sort itself out :(

**Comment by wwwouter** [comment]
Hi, I haven't seen that before. Could you share the table classes? And what are the specs of your machine (CPU,mem)?

**Comment by wwwouter** [comment]
@tecorraltd Do you still have this problem, or can this issue be closed?
