### ISSUE TITLE
ValidateTables with multiple databases

### ISSUE THREAD

**Issue by MichielHegemans** [wwwouter/typed-knex#60]
**Issue type:**

- [ ] Question
- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue

**Database system/driver:**

- [x] Postgres
- [x] MSSQL
- [x] MySQL
- [x] MariaDB
- [x] SQLite3
- [x] Oracle
- [x] Amazon Redshift

**typed-knex version:**

- [ ] `latest`
- [ ] `@next`
- [x] `4.9.1`

**Knex.js version:**

**Steps to reproduce or a small repository showing the problem:**

I want to use TypedKnex to connect to more than 1 database and validate the tables in each of those databases. The databases do not contain the same tables.

I want to have something like this:
```ts
const knex1 = Knex({ client: 'pg', connection: 'someString' });
await validateTables(knex1, [Table1, Table2]);
const knex2 = Knex({ client: 'pg', connection: 'someOtherString' });
await validateTables(knex2, [Table3, Table4]);
```

When I use `validateTables` now it will complain that not all the tables exist in both databases.

**Comment by wwwouter** [comment]
Yeah, that's a small change. Can you checkout v4.11.0?
