### ISSUE TITLE
Select autocomplete dropdown breaks with TypeScript v4.7.x

### ISSUE THREAD

**Issue by voinik** [wwwouter/typed-knex#63]
**Issue type:**

[ ] Question
[X] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[X] Postgres
[ ] MSSQL
[ ] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[ ] `latest`
[ ] `@next`
[4.12.0] `0.x.x` (or put your version here)

**Knex.js version:**
2.2.0

**Steps to reproduce or a small repository showing the problem:**
1. Type this using any model with more than 1 property in it: 
```ts
typedKnex.query(User).select('id');
```
2. try to add more properties in the select and you'll find the only choices you have in the dropdown are the keys you already have in there, rather than **all** keys.

I've tested the following versions of TypeScript: 4.4.4, 4.5.4, 4.6.2, 4.6.4. This bug did not appear in these versions. The bug starts appearing in versions 4.7.2 and higher.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] Postgres
    [ ] MSSQL

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by wwwouter** [comment]
This seems to be fixed in version [4.8.1-rc](https://www.npmjs.com/package/typescript/v/4.8.1-rc) 
I'm waiting for the official 4.8 release before investigating further.

**Comment by wwwouter** [comment]
Should be released tomorrow https://github.com/microsoft/TypeScript/issues/49074

**Comment by wwwouter** [comment]
4.8 is released! Can you check if it works again?

**Comment by voinik** [comment]
Great, it works again! Closing this
