### ISSUE TITLE
Table decorator is incorrectly marked as deprecated

### ISSUE THREAD

**Issue by isRyven** [wwwouter/typed-knex#65]
**Issue type:**

[ ] Question
[x] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[x] Postgres
[ ] MSSQL
[ ] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[ ] `latest`
[ ] `@next`
[x] `4.13.0`

**Knex.js version:**
`2.2.0`

**Typescript version:**
`4.7.4`

**Steps to reproduce or a small repository showing the problem:**

I have block like this, which i've built following the documentation:

```ts
import { Column, Table } from '@wwwouter/typed-knex';

@Table('user')
class User {
    @Column({ primary: true })
    public id: number;
    @Column()
    public username: string;
    @Column()
    public email: string;
    @Column({ name: 'first_name' })
    public firstName: string;
    @Column({ name: 'last_name' })
    public lastName: string;
}
```

But my vscode keeps showing a warning that the `Table` decorator is deprecated.
`Table is deprecated. use Table`.

![image](https://user-images.githubusercontent.com/14905030/186162747-c9001944-4126-43c2-9d94-cb00ad2283e1.png)

**Comment by wwwouter** [comment]
`Table` was using `Entity`, and I think sonarlint thought `Table` should be deprecated as well. I changed it in v4.13.1, could you test to see if this removes the warning?

**Comment by isRyven** [comment]
Thank you for your quick reaction kind sir, it has indeed resolved the issue!
